[project]
name = "bir_waqf"
authors = [
    { name = "Antigravity", email = "info@waqf.ly"}
]
description = "نظام معالجة بيانات ومطابقة البر الوقفية"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "pandas",
    "openpyxl"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
